import P1 from "@/assets/images/p1.jpg";
import P2 from "@/assets/images/p2.jpg";

export const productsData = [
	{
		src: P1,
		isSale: false,
		isFav: true,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P2,
		isSale: false,
		isFav: false,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P2,
		isSale: true,
		isFav: true,
		title: "Jeep Car, new, used for only one time",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P1,
		isSale: false,
		isFav: false,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P2,
		isSale: true,
		isFav: false,
		title: "Jeep Car, new, used for only one time",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P1,
		isSale: false,
		isFav: true,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P2,
		isSale: false,
		isFav: false,
		title: "Jeep Car, new, used for only one time",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P1,
		isSale: true,
		isFav: false,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
];

export const articlesData = [
	{
		src: P1,
		isSale: true,
		isFav: false,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P2,
		isSale: false,
		isFav: false,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P2,
		isSale: true,
		isFav: true,
		title: "Jeep Car, new, used for only one time",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P1,
		isSale: true,
		isFav: false,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P2,
		isSale: false,
		isFav: false,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P2,
		isSale: true,
		isFav: true,
		title: "Jeep Car, new, used for only one time",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
];

export const reviewsData = [
	{
		src: P1,
		isSale: false,
		isFav: true,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P2,
		isSale: false,
		isFav: false,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P2,
		isSale: true,
		isFav: true,
		title: "Jeep Car, new, used for only one time",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P1,
		isSale: true,
		isFav: false,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
	{
		src: P2,
		isSale: false,
		isFav: false,
		title: "Six-piece clothing set (blouse - pants - hat and ...",
		price: 1000,
		days: 2,
		hours: 10,
		minutes: 50,
	},
];
